{{- if .Values.networkPolicy.create -}}
{{- range .Values.namespaces }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ . }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
{{- end }}
{{- end -}}
