kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-manager
  labels:
    app: {{ template "cluster-admin.name" . }}
    chart: {{ template "cluster-admin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "ingresses"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete", "deletecollection"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-manager
  labels:
    app: {{ template "cluster-admin.name" . }}
    chart: {{ template "cluster-admin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: netpolicy-manager
  labels:
    app: {{ template "cluster-admin.name" . }}
    chart: {{ template "cluster-admin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: ["extensions"]
  resources: ["networkpolicies"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
# Dashboard only has read-only access and list access to secrets
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: cluster-viewer
  labels:
    app: {{ template "cluster-admin.name" . }}
    chart: {{ template "cluster-admin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  - nodes
  verbs:
  - get
  - list
  - watch
---
# Dashboard only has read-only access and list access to secrets
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-lister
  labels:
    app: {{ template "cluster-admin.name" . }}
    chart: {{ template "cluster-admin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
