apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvcName }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: "Delete"
  capacity:
    storage: "{{ .Values.size }}"
  accessModes:
    - "{{ .Values.accessMode }}"
  gcePersistentDisk:
    pdName: "{{ .Values.gcePdName }}"
    fsType: ext4
