apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rails-app.fullname" . }}
  labels:
    app: {{ template "rails-app.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  db-user: {{ .Values.postgresql.postgresUser | b64enc | quote }}
  db-password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  secret-key-base: {{ "ad784b536e49fb54575dd71d1fc6c0f3310cc70aa5a200718cda2d6847bd3f9223fae14464a596f0028316bd1af5e8265d77261aac21b7e907fb1b6c944fb86b" | b64enc }}
