# List namespaces to create
# Use 'secure: true' to add deny-all networkpolicy + allow-dns networkpolicy
namespaces: []
# - name: team1
#   secure: false
# - name: team2
#   secure: true

# Assign cluster-admin role to users
clusterAdmins:
  create: false
  users: []
    # - user@example.com

# List roles to limit things you can view / modify with the dashboard
# By default, you only get the "view" role
dashboardPermissions:
  create: true
  clusterRoles:
    - view
    # - secret-lister
    # - cluster-object-viewer
