apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "drone.fullname" . }}-server
  labels:
    app: {{ template "drone.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "drone.name" . }}
        release: "{{ .Release.Name }}"
        component: server
    spec:
      containers:
      - name: {{ template "drone.fullname" . }}-server
        image: "{{ .Values.images.server.repository }}:{{ .Values.images.server.tag }}"
        imagePullPolicy: {{ .Values.images.server.pullPolicy }}
        env:

          - name: DRONE_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "drone.fullname" . }}
                key: secret

          - name: DRONE_HOST
          {{- if hasKey .Values.server "host" }}
            value: {{ .Values.server.host }}
          {{- else }}
            value: {{ template "drone.fullname" . }}
          {{- end }}

          {{- if .Values.server.githubAuth.enabled }}
          - name: DRONE_OPEN
            value: {{ quote .Values.server.githubAuth.openRegistration }}

          - name: DRONE_PROVIDER
            value: github

          - name: DRONE_GITHUB
            value: "true"

          - name: DRONE_GITHUB_CLIENT
            valueFrom:
              secretKeyRef:
                name: {{ template "drone.fullname" . }}
                key: github-auth-client-id

          - name: DRONE_GITHUB_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "drone.fullname" . }}
                key: github-auth-client-secret

          {{- if .Values.server.githubAuth.orgs }}
          - name: DRONE_ORGS
            value: {{ .Values.server.githubAuth.orgs }}
          {{- end }}

          - name: DRONE_ADMIN
            value: {{ .Values.server.githubAuth.admin }}
          {{ end }}
          {{ range $key, $value := .Values.server.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{ end }}

        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: grpc
          containerPort: 9000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        resources:
{{ toYaml .Values.server.resources | indent 10 }}
        volumeMounts:
          - name: data
            mountPath: /var/lib/drone
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "drone.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
