{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "drone.fullname" . }}
  labels:
    app: {{ template "drone.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.server.githubAuth.enabled }}
  github-auth-client-id: {{ default "" .Values.secrets.server.githubAuth.clientId | b64enc | quote }}
  github-auth-client-secret: {{ default "" .Values.secrets.server.githubAuth.clientSecret | b64enc | quote }}
  {{- end }}
  {{ if .Values.sharedSecret }}
  secret: "{{ .Values.sharedSecret | b64enc }}"
  {{ else }}
  secret: "{{ randAlphaNum 24 | b64enc }}"
  {{- end }}
{{- end }}
