{{- if .Values.networkPolicy.enabled -}}
# Allow traffic from api to team2 payments module through grpc
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "demo-api.fullname" . }}-egress
spec:
  policyTypes:
  - Egress
  podSelector:
    matchLabels:
      app: {{ template "demo-api.name" . }}
      release: {{ .Release.Name }}
  egress:
  - ports:
    - port: {{ .Values.payments.port }}
      protocol: TCP
    to:
    - namespaceSelector: # no PodSelector, allow to all pods in this namespace
        matchLabels:
          name: {{ .Values.payments.namespace }}
{{- end -}}
