apiVersion: v1
kind: Service
metadata:
  name: {{ template "demo-api.fullname" . }}
  labels:
    app: {{ template "demo-api.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "demo-api.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - name: endpoint
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }
